### ISSUE TITLE
Not converting non empty lines

### ISSUE THREAD

**Issue by Radivarig** [icelab/draft-js-autolist-plugin#13]
If there is already text typed on a line it does not get converted. `[type text][go to line start][-][space]`

**Comment by makenosound** [comment]
This is actually intended behaviour (you can see it [outlined in the "Caveats" section of the README](https://github.com/icelab/draft-js-autolist-plugin#caveats)).

This was done partly to avoid thrashing the editor to check for these sequences all the time, and also because there are legitimate reasons to want to start a paragraph with a `* ` sequence without wanting it converted to a list.
