### ISSUE TITLE
keyBindingFn not working in autolist plugin when implementing my own

### ISSUE THREAD

**Issue by alekhurst** [icelab/draft-js-autolist-plugin#14]
This plugin has been great! One problem I've come across is when I create my own `keyBindingFn` and pass it into `PluginsEditor`  as a prop like so:

```
<PluginsEditor keyBindingFn={this.keyBindingFn} />
```

The keyBindingFn in autolist no longer works, meaning it no longer converts the block to a `unordered-list-item` or `ordered-list-item` when typing `* ` or `1. `.

When I remove my own `keyBindingFn`, it works again.

**Comment by makenosound** [comment]
@alekhurst Ah, boo. There are a couple of things it could be:

1. I think `keyBindingFn` is basically first come, first serve, so if your function returns a value it may not run any additional `keyBindingFn` methods.
2. It’s possible that the `PluginsEditor` just overrides any plugin-`keyBindingFn`s when you specify your own at the top level like this.

In the case of 2, you could create a very simply plugin inline that simply defines the same `keyBindingFn` that you’re passing in.

```js
const inlinePlugin {
  keyBindingFn (e) {
    // Do your thing here.
  }
}

<PluginsEditor plugins={[autoListPlugin, inlinePlugin]} />
```

I don’t think there’s anything I can change in this plugin to stop that behaviour happening, alas, so I’ll close this here. If the latter doesn’t work for you then it’s likely an issue you’ll need to raise with `draft-js-plugins` rather than here!

**Comment by schlosser** [comment]
+1 on this, just spent at least an hour debugging this problem. Even if it's likely an issue with `draft-js-plugins`'s interface, it should probably be noted in your README!

**Comment by timriley** [comment]
@schlosser We'd be happy to accept a PR with a README note :)
