### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by stevensacks** [icelab/draft-js-autolist-plugin#16]
I have a brand new installation of the editor. This is the only plugin I have installed. It's not working. I type `-` or `*` and space and it never makes a list.

react 16.9.0
draft-js 0.11.1
draft-js-plugins-editor 3.0.0
draft-js-autolist-plugin 2.0.0

**Comment by cmoad** [comment]
Also seeing this. I suspect it's related to the draft 0.11.x upgrade.

**Comment by amannn** [comment]
The bug is here:
https://github.com/icelab/draft-js-autolist-plugin/blob/6abe2c5352c13ee4ade3626addb36e18cef2d9cd/src/index.js#L121

In the latest version of draftjs-plugins-editor a new parameter was added: https://github.com/draft-js-plugins/draft-js-plugins/pull/1303/files#diff-8ba3abec38e74b4fedeec7a96faee909R39

**Comment by jrock17** [comment]
Can we get the fix merged here?

**Comment by makenosound** [comment]
Sorry for the delay folks. Closing a company, starting a new job, hiding during a pandemic. Should be released as v3.0.0
